Traceback (most recent call last):
  File "/home/hadoop/program/total_scripts/02jpg_upload_hdfs_20180607_debug_single_v1_06.py", line 124, in <module>
    handle()
  File "/home/hadoop/program/total_scripts/02jpg_upload_hdfs_20180607_debug_single_v1_06.py", line 112, in handle
    uploadHDFS(newname)
  File "/home/hadoop/program/total_scripts/02jpg_upload_hdfs_20180607_debug_single_v1_06.py", line 81, in uploadHDFS
    client.upload(hdfs_path+folder1+"/"+aoi_file,upload_path+aoi_file,overwrite=True)
  File "/usr/local/lib/python2.7/site-packages/hdfs/client.py", line 605, in upload
    raise err
requests.exceptions.ConnectionError: [Errno 104] Connection reset by peer
